[alias]
rr = "run --release"
br = "build --release"
cr = "check --release"
f = "fmt"
con = "run --release --bin concurrent"
seq = "run --release --bin sequencial"

[build]
target = "x86_64-unknown-linux-musl"
rustflags = ["-C","target-cpu=native"]