[package]
name = "concurrent"
version = "0.1.2"
authors = ["Abner Kaizer <abnerkaizer@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

threadpool = "1.8.1"
num_cpus = "1.13.0"